### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by ghost** [Paguiar735/whatsmeow-quickstart#1]
panic: couldn't dial whatsapp web websocket: EOF

**Comment by codespearhead** [comment]
Can you try one of the quickstarts again? I pushed a new commit about 10 hours ago.

In the past three days I've been testing out a [CGo-free implementation of SQLite](https://gitlab.com/cznic/sqlite) to try releasing the [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) as a standalone executable file. However, I realized that that implementation didn't work well with WhatsMeow, so I rebased the commit out of existence.

If the problem persists, does the bot answer with "pong" after you send "ping" to it?
